// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdGNNTc7d9khWvPyZ4MpD50ETnITifaJU',
    appId: '1:390053117087:web:672bbbba211d52423776aa',
    messagingSenderId: '390053117087',
    projectId: 'swim-38b51',
    authDomain: 'swim-38b51.firebaseapp.com',
    storageBucket: 'swim-38b51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQapMLAn1yuXl_-ET5WYNnP9EBD7XahCE',
    appId: '1:390053117087:android:d65fe1b29eeaf1ff3776aa',
    messagingSenderId: '390053117087',
    projectId: 'swim-38b51',
    storageBucket: 'swim-38b51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDdzbbFTZQmXmYs1tDcswFH4E8oYyaesw',
    appId: '1:390053117087:ios:6ffdfdb9578a3a333776aa',
    messagingSenderId: '390053117087',
    projectId: 'swim-38b51',
    storageBucket: 'swim-38b51.firebasestorage.app',
    iosBundleId: 'com.example.swim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDdzbbFTZQmXmYs1tDcswFH4E8oYyaesw',
    appId: '1:390053117087:ios:6ffdfdb9578a3a333776aa',
    messagingSenderId: '390053117087',
    projectId: 'swim-38b51',
    storageBucket: 'swim-38b51.firebasestorage.app',
    iosBundleId: 'com.example.swim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdGNNTc7d9khWvPyZ4MpD50ETnITifaJU',
    appId: '1:390053117087:web:97c066e8e16772b73776aa',
    messagingSenderId: '390053117087',
    projectId: 'swim-38b51',
    authDomain: 'swim-38b51.firebaseapp.com',
    storageBucket: 'swim-38b51.firebasestorage.app',
  );
}
